enum WorkoutTitle {
  UPPER_A = 'UpperA',
  UPPER_B = 'UpperB',
  LOWER = 'Lower',
}

const WORKOUTS = {
  [WorkoutTitle.UPPER_A]: {
    title: 'Upper A',
    exercices: {
      first: {
        name: 'Développé couché incliné',
        reps: ['6', '8', '10'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      second: {
        name: 'Tractions lestées',
        reps: ['6', '8', '10'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      third: {
        name: 'Élévations Frontales (pecs)',
        reps: ['15', '15', '15'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      fourth: {
        name: 'Curl incliné haltères',
        reps: ['12', '12', '12'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      fifth: {
        name: 'Élévations latérales',
        reps: ['20', '15', '10'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
    },
  },
  [WorkoutTitle.LOWER]: {
    title: 'Lower',
    exercices: {
      first: {
        name: 'High bar squat / Deadlift',
        reps: ['10', '10', '10'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      second: {
        name: 'Romanian deadlift / Fentes',
        reps: ['15', '15', '15'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      third: {
        name: 'Leg curl superset - Leg extension',
        reps: ['12', '12', '12'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      fourth: {
        name: 'Extensions mollets',
        reps: ['15', '12', '10'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      fifth: {
        name: 'Upright row penché',
        reps: ['20', '15', '10'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
    },
  },
  [WorkoutTitle.UPPER_B]: {
    title: 'Upper B',
    exercices: {
      first: {
        name: 'Overhead press',
        reps: ['6', '8', '10'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      second: {
        name: 'Développé couché',
        reps: ['6', '8', '10'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      third: {
        name: 'Tractions prise neutre',
        reps: ['12', '12', '12'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      fourth: {
        name: 'Oiseau assis prise neutre',
        reps: ['15', '15', '15'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
      fifth: {
        name: 'Upright row',
        reps: ['15', '12', '10'],
        firstSet: '',
        secondSet: '',
        thirdSet: '',
        weight: '',
      },
    },
  },
}

export { WORKOUTS, WorkoutTitle }
